# Site settings
title: CIENCIAS DE LA COMPUTACION 2
year: 2018
slack_page: https://cc2-2018.slack.com
footerlogo: logo-footer.png
descripcion: >
 Pagina del curso CC2 - Universidad Galileo
baseurl: ""
url: "localhost:4000"

# Build settings
markdown: kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
